syntax = "proto3";

package notification.v1;

service NotificationService {
  rpc SendNotification(SendNotificationRequest) returns (SendNotificationResponse);
  rpc ReadNotification(ReadNotificationRequest) returns (ReadNotificationResponse);
  rpc GetNotifications(GetNotificationsRequest) returns (GetNotificationsResponse);
}

enum NotificationType {
  GUILD_MEMBER_ADD = 0;
  GUILD_MEMBER_LEAVE = 1;
  NEW_INVITE_TO_GUILD = 2;
}

message SendNotificationRequest {
  string sender_id = 1;
  string receiver_id = 2;
  string notification_payload = 3;
  string channel = 4;
  NotificationType notification_type = 5;
}

message SendNotificationResponse {
  Notification notification = 1;
}

message ReadNotificationRequest {
  repeated string notification_ids = 1;
}

message ReadNotificationResponse {
  bool status = 1;
}

message GetNotificationsRequest {
  oneof identifier {
    string sender_id = 1;
    string receiver_id = 2;
  }
}

message GetNotificationsResponse {
  repeated Notification notifications = 1;
}

message Notification {
  string id = 1;
  string sender_id = 2;
  string receiver_id = 3;
  string notification_payload = 4;
  string created_at = 5;
  bool is_read = 6;
  NotificationType notification_type = 7;
}
